version: v0.5-{build}

image: Visual Studio 2019

init:
  - set WB2TAG=v0.5
  - wsl lsb_release -a

before_build:
  - C:\msys64\usr\bin\bash.exe --login -c "git clone https://github.com/Biswa96/wslbridge2.git -b %WB2TAG% --depth 1"

build_script:
  - C:\msys64\usr\bin\bash.exe --login -c "cd wslbridge2 && pwd && make RELEASE=1"
  - C:\msys64\usr\bin\bash.exe --login -c "ls -l wslbridge2/bin/*.exe"
  - copy C:\msys64\home\appveyor\wslbridge2\bin\*.exe .

after_build:
  - cd
  - dir *.exe
  - sha256sum wslbridge2.exe > wslbridge2.exe.sha256
  - sha256sum rawpty.exe > rawpty.exe.sha256

artifacts:
  - path: wslbridge2.exe
  - path: wslbridge2.exe.sha256
  - path: rawpty.exe
  - path: rawpty.exe.sha256

